---

#- name: Get ubuntu ubuntu_version
#- debug: var=ansible_facts

- name: Import tasks if its debian os family
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: get vars
  vars: 
    my_var: "This is {{ansible_facts['lsb']['codename']}} version of ubuntu"
  debug: 
    var: my_var

- name: Add an Apt signing key, uses whichever key is at the URL for nginx
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present
  # notify: update repo

# - name: Remove unsupportet repo
#   apt_repository:
#     repo: deb http://archive.getdeb.net/ubuntu
#     state: absent

- name: Add a nginx repository
  apt_repository:
    repo: deb http://nginx.org/packages/ubuntu {{ansible_facts['lsb']['codename']}} nginx
    state: present
  # notify: update repo

#- meta: flush_handlers

- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: true
    force_apt_get: yes

- name: Enable nginx
  service: 
    name: nginx
    enabled: yes
    state: started





#echo "deb http://nginx.org/packages/ubuntu `lsb_release -cs` nginx"     | sudo tee /etc/apt/sources.list.d/nginx.list
#curl -fsSL https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
#sudo apt-get update
#sudo apt-get install nginx -y
#sudo service nginx enable
#sudo cp /home/vagrant/wrdprs.conf /etc/nginx/conf.d/
#sudo service nginx restart